mkdir -p ~/Desktop/NSF_Dynamical/v4_images
cp uniamp/original/plots/hq_original.png ~/Desktop/NSF_Dynamical/v4_images/uniamp_original.png
cp uniamp/leaky/plots/hq_leaky.png ~/Desktop/NSF_Dynamical/v4_images/uniamp_leaky.png
cp uniamp/leaky_shadow/plots/hq_leaky_shadow.png ~/Desktop/NSF_Dynamical/v4_images/uniamp_leaky_shadow.png
cp biamp/original/plots/hq_original.png ~/Desktop/NSF_Dynamical/v4_images/biamp_original.png
cp biamp/leaky/plots/hq_leaky.png ~/Desktop/NSF_Dynamical/v4_images/biamp_leaky.png
cp biamp/leaky_shadow/plots/hq_leaky_shadow.png ~/Desktop/NSF_Dynamical/v4_images/biamp_leaky_shadow.png
cp rps/original/plots/hq_original.png ~/Desktop/NSF_Dynamical/v4_images/rps_original.png
cp rps/leaky/plots/hq_leaky.png ~/Desktop/NSF_Dynamical/v4_images/rps_leaky.png
cp rps/leaky_shadow/plots/hq_leaky_shadow.png ~/Desktop/NSF_Dynamical/v4_images/rps_leaky_shadow.png
cp con/original/plots/hq_original.png ~/Desktop/NSF_Dynamical/v4_images/con_original.png
cp con/leaky/plots/hq_leaky.png ~/Desktop/NSF_Dynamical/v4_images/con_leaky.png
cp con/leaky_shadow/plots/hq_leaky_shadow.png ~/Desktop/NSF_Dynamical/v4_images/con_leaky_shadow.png
cp rps/0_4/plots/hq_orig_shadow_pert_cancel.png ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert-1.5x_cancel.png
cp rps/1/plots/hq_orig_shadow_pert_cancel.png ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert-2x_cancel.png
cp rps/4/plots/hq_orig_shadow_pert_cancel.png ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert-5x_cancel.png
cp rps/9/plots/hq_orig_shadow_pert_cancel.png ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert-10x_cancel.png
#  
cp rps/9/plots/hq_orig_shadow_pert_nocancel_cancel_combined.png ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert_cancel_nocancel_combined.png
cp rps/1/plots/hq_orig_shadow_pert_cancel_2X.png  ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert_cancel_2X.png
cp rps/1/plots/hq_orig_shadow_pert_cancel_2X_withprimary.png  ~/Desktop/NSF_Dynamical/v4_images/rps_original_shadow_pert_cancel_2X_withprimary.png
cp control/original/plots/hq_r1_cat.png ~/Desktop/NSF_Dynamical/v4_images/hq_r1_cat.png
cp control/original/plots/hq_r4_deg.png ~/Desktop/NSF_Dynamical/v4_images/hq_r4_deg.png
cp control/original/plots/hq_r11_ann.png ~/Desktop/NSF_Dynamical/v4_images/hq_r11_ann.png
