#!/usr/bin/env python
"""
A template file to simulate a specific system of Ordinary Differential Equations (ODEs).

... or an autogenerated script from the *crnsimulator* Python package.

Note: If this file is executable, it is *autogenerated*.
    This means it contains a system of hardcoded ODEs together with some
    default parameters. While it may be tempting to tweak some functions,
    beware that this file may be overwritten by the next execution of the
    `crnsimulator` executable.  Edits should be done at the source file:
    "crnsimulator.odelib_template.py" or you can provide an alternative
    template file. Use the option --output to avoid overwriting this file.

Usage: 
    python odesystem.py --help
"""

import logging
logger = logging.getLogger(__name__)

import argparse
import numpy as np
from scipy.integrate import odeint

class ODETemplateError(Exception):
    pass

rates = {
    
}

def odesystem(p0, t0, r):
    Ak, Br, Cj, BackAC, BackBA, BackCB, HelperAAk, HelperBBr, HelperCCj, M10, M112, M146, M160, M163, M203, M206, M30, M5, M55, M56, M60, M69, M70, M75, M87, M9, M91, ProduceABrBr, ProduceBCjCj, ProduceCAkAk, ReactACAk, ReactBABr, ReactCBCj = p0
    if not r : r = rates


    dAkdt = -0.00104769*Ak*M146 - 0.0020865*Ak*M60 - 0.00104661*Ak*ReactACAk + 0.00104661*BackAC*M5 + 0.00383326*HelperAAk*M146 + 0.00175818*M10*M163 + 0.00104769*M10*ProduceCAkAk
    dBrdt = 0.00104661*BackBA*M60 - 0.0020865*Br*M30 - 0.00104769*Br*M75 - 0.00104661*Br*ReactBABr + 0.00383326*HelperBBr*M75 + 0.00175818*M69*M91 + 0.00104769*M69*ProduceABrBr
    dCjdt = 0.00104661*BackCB*M30 - 0.00104769*Cj*M112 - 0.0020865*Cj*M5 - 0.00104661*Cj*ReactCBCj + 0.00383326*HelperCCj*M112 + 0.00175818*M206*M56 + 0.00104769*M56*ProduceBCjCj
    dBackACdt = 0.00104661*Ak*ReactACAk - 0.00104661*BackAC*M5
    dBackBAdt = -0.00104661*BackBA*M60 + 0.00104661*Br*ReactBABr
    dBackCBdt = -0.00104661*BackCB*M30 + 0.00104661*Cj*ReactCBCj
    dHelperAAkdt = -0.0038442886*HelperAAk*M146 + 0.000330858*M10*M163
    dHelperBBrdt = -0.0038442886*HelperBBr*M75 + 0.000330858*M69*M91
    dHelperCCjdt = -0.0038442886*HelperCCj*M112 + 0.000330858*M206*M56
    dM10dt = 0.00104769*Ak*M146 + 0.0020865*Cj*M5 + 1.10286e-5*HelperAAk*M146 - 0.002089038*M10*M163 - 0.00104769*M10*ProduceCAkAk
    dM112dt = -0.00104769*Cj*M112 - 0.0038442886*HelperCCj*M112 + 0.000330858*M206*M56 + 0.00104769*M56*ProduceBCjCj
    dM146dt = -0.00104769*Ak*M146 - 0.0038442886*HelperAAk*M146 + 0.000330858*M10*M163 + 0.00104769*M10*ProduceCAkAk
    dM160dt = 0.00383326*HelperAAk*M146 + 0.00175818*M10*M163
    dM163dt = 1.10286e-5*HelperAAk*M146 - 0.002089038*M10*M163
    dM203dt = 0.00383326*HelperCCj*M112 + 0.00175818*M206*M56
    dM206dt = 1.10286e-5*HelperCCj*M112 - 0.002089038*M206*M56
    dM30dt = -0.00104661*BackCB*M30 - 0.0020865*Br*M30 + 0.00104661*Cj*ReactCBCj
    dM5dt = 0.00104661*Ak*ReactACAk - 0.00104661*BackAC*M5 - 0.0020865*Cj*M5
    dM55dt = 0.0020865*Br*M30
    dM56dt = 0.0020865*Br*M30 + 0.00104769*Cj*M112 + 1.10286e-5*HelperCCj*M112 - 0.002089038*M206*M56 - 0.00104769*M56*ProduceBCjCj
    dM60dt = -0.0020865*Ak*M60 - 0.00104661*BackBA*M60 + 0.00104661*Br*ReactBABr
    dM69dt = 0.0020865*Ak*M60 + 0.00104769*Br*M75 + 1.10286e-5*HelperBBr*M75 - 0.002089038*M69*M91 - 0.00104769*M69*ProduceABrBr
    dM70dt = 0.0020865*Ak*M60
    dM75dt = -0.00104769*Br*M75 - 0.0038442886*HelperBBr*M75 + 0.000330858*M69*M91 + 0.00104769*M69*ProduceABrBr
    dM87dt = 0.00383326*HelperBBr*M75 + 0.00175818*M69*M91
    dM9dt = 0.0020865*Cj*M5
    dM91dt = 1.10286e-5*HelperBBr*M75 - 0.002089038*M69*M91
    dProduceABrBrdt = 0.00104769*Br*M75 - 0.00104769*M69*ProduceABrBr
    dProduceBCjCjdt = 0.00104769*Cj*M112 - 0.00104769*M56*ProduceBCjCj
    dProduceCAkAkdt = 0.00104769*Ak*M146 - 0.00104769*M10*ProduceCAkAk
    dReactACAkdt = -0.00104661*Ak*ReactACAk + 0.00104661*BackAC*M5
    dReactBABrdt = 0.00104661*BackBA*M60 - 0.00104661*Br*ReactBABr
    dReactCBCjdt = 0.00104661*BackCB*M30 - 0.00104661*Cj*ReactCBCj
    return np.array([dAkdt, dBrdt, dCjdt, dBackACdt, dBackBAdt, dBackCBdt, dHelperAAkdt, dHelperBBrdt, dHelperCCjdt, dM10dt, dM112dt, dM146dt, dM160dt, dM163dt, dM203dt, dM206dt, dM30dt, dM5dt, dM55dt, dM56dt, dM60dt, dM69dt, dM70dt, dM75dt, dM87dt, dM9dt, dM91dt, dProduceABrBrdt, dProduceBCjCjdt, dProduceCAkAkdt, dReactACAkdt, dReactBABrdt, dReactCBCjdt])

def jacobian(p0, t0, r):
    Ak, Br, Cj, BackAC, BackBA, BackCB, HelperAAk, HelperBBr, HelperCCj, M10, M112, M146, M160, M163, M203, M206, M30, M5, M55, M56, M60, M69, M70, M75, M87, M9, M91, ProduceABrBr, ProduceBCjCj, ProduceCAkAk, ReactACAk, ReactBABr, ReactCBCj = p0
    if not r : r = rates


    J = [[[] for i in range(len(p0))] for j in range(len(p0))]
    J[0][0] = -0.00104769*M146 - 0.0020865*M60 - 0.00104661*ReactACAk
    J[0][1] = 0
    J[0][2] = 0
    J[0][3] = 0.00104661*M5
    J[0][4] = 0
    J[0][5] = 0
    J[0][6] = 0.00383326*M146
    J[0][7] = 0
    J[0][8] = 0
    J[0][9] = 0.00175818*M163 + 0.00104769*ProduceCAkAk
    J[0][10] = 0
    J[0][11] = -0.00104769*Ak + 0.00383326*HelperAAk
    J[0][12] = 0
    J[0][13] = 0.00175818*M10
    J[0][14] = 0
    J[0][15] = 0
    J[0][16] = 0
    J[0][17] = 0.00104661*BackAC
    J[0][18] = 0
    J[0][19] = 0
    J[0][20] = -0.0020865*Ak
    J[0][21] = 0
    J[0][22] = 0
    J[0][23] = 0
    J[0][24] = 0
    J[0][25] = 0
    J[0][26] = 0
    J[0][27] = 0
    J[0][28] = 0
    J[0][29] = 0.00104769*M10
    J[0][30] = -0.00104661*Ak
    J[0][31] = 0
    J[0][32] = 0
    J[1][0] = 0
    J[1][1] = -0.0020865*M30 - 0.00104769*M75 - 0.00104661*ReactBABr
    J[1][2] = 0
    J[1][3] = 0
    J[1][4] = 0.00104661*M60
    J[1][5] = 0
    J[1][6] = 0
    J[1][7] = 0.00383326*M75
    J[1][8] = 0
    J[1][9] = 0
    J[1][10] = 0
    J[1][11] = 0
    J[1][12] = 0
    J[1][13] = 0
    J[1][14] = 0
    J[1][15] = 0
    J[1][16] = -0.0020865*Br
    J[1][17] = 0
    J[1][18] = 0
    J[1][19] = 0
    J[1][20] = 0.00104661*BackBA
    J[1][21] = 0.00175818*M91 + 0.00104769*ProduceABrBr
    J[1][22] = 0
    J[1][23] = -0.00104769*Br + 0.00383326*HelperBBr
    J[1][24] = 0
    J[1][25] = 0
    J[1][26] = 0.00175818*M69
    J[1][27] = 0.00104769*M69
    J[1][28] = 0
    J[1][29] = 0
    J[1][30] = 0
    J[1][31] = -0.00104661*Br
    J[1][32] = 0
    J[2][0] = 0
    J[2][1] = 0
    J[2][2] = -0.00104769*M112 - 0.0020865*M5 - 0.00104661*ReactCBCj
    J[2][3] = 0
    J[2][4] = 0
    J[2][5] = 0.00104661*M30
    J[2][6] = 0
    J[2][7] = 0
    J[2][8] = 0.00383326*M112
    J[2][9] = 0
    J[2][10] = -0.00104769*Cj + 0.00383326*HelperCCj
    J[2][11] = 0
    J[2][12] = 0
    J[2][13] = 0
    J[2][14] = 0
    J[2][15] = 0.00175818*M56
    J[2][16] = 0.00104661*BackCB
    J[2][17] = -0.0020865*Cj
    J[2][18] = 0
    J[2][19] = 0.00175818*M206 + 0.00104769*ProduceBCjCj
    J[2][20] = 0
    J[2][21] = 0
    J[2][22] = 0
    J[2][23] = 0
    J[2][24] = 0
    J[2][25] = 0
    J[2][26] = 0
    J[2][27] = 0
    J[2][28] = 0.00104769*M56
    J[2][29] = 0
    J[2][30] = 0
    J[2][31] = 0
    J[2][32] = -0.00104661*Cj
    J[3][0] = 0.00104661*ReactACAk
    J[3][1] = 0
    J[3][2] = 0
    J[3][3] = -0.00104661*M5
    J[3][4] = 0
    J[3][5] = 0
    J[3][6] = 0
    J[3][7] = 0
    J[3][8] = 0
    J[3][9] = 0
    J[3][10] = 0
    J[3][11] = 0
    J[3][12] = 0
    J[3][13] = 0
    J[3][14] = 0
    J[3][15] = 0
    J[3][16] = 0
    J[3][17] = -0.00104661*BackAC
    J[3][18] = 0
    J[3][19] = 0
    J[3][20] = 0
    J[3][21] = 0
    J[3][22] = 0
    J[3][23] = 0
    J[3][24] = 0
    J[3][25] = 0
    J[3][26] = 0
    J[3][27] = 0
    J[3][28] = 0
    J[3][29] = 0
    J[3][30] = 0.00104661*Ak
    J[3][31] = 0
    J[3][32] = 0
    J[4][0] = 0
    J[4][1] = 0.00104661*ReactBABr
    J[4][2] = 0
    J[4][3] = 0
    J[4][4] = -0.00104661*M60
    J[4][5] = 0
    J[4][6] = 0
    J[4][7] = 0
    J[4][8] = 0
    J[4][9] = 0
    J[4][10] = 0
    J[4][11] = 0
    J[4][12] = 0
    J[4][13] = 0
    J[4][14] = 0
    J[4][15] = 0
    J[4][16] = 0
    J[4][17] = 0
    J[4][18] = 0
    J[4][19] = 0
    J[4][20] = -0.00104661*BackBA
    J[4][21] = 0
    J[4][22] = 0
    J[4][23] = 0
    J[4][24] = 0
    J[4][25] = 0
    J[4][26] = 0
    J[4][27] = 0
    J[4][28] = 0
    J[4][29] = 0
    J[4][30] = 0
    J[4][31] = 0.00104661*Br
    J[4][32] = 0
    J[5][0] = 0
    J[5][1] = 0
    J[5][2] = 0.00104661*ReactCBCj
    J[5][3] = 0
    J[5][4] = 0
    J[5][5] = -0.00104661*M30
    J[5][6] = 0
    J[5][7] = 0
    J[5][8] = 0
    J[5][9] = 0
    J[5][10] = 0
    J[5][11] = 0
    J[5][12] = 0
    J[5][13] = 0
    J[5][14] = 0
    J[5][15] = 0
    J[5][16] = -0.00104661*BackCB
    J[5][17] = 0
    J[5][18] = 0
    J[5][19] = 0
    J[5][20] = 0
    J[5][21] = 0
    J[5][22] = 0
    J[5][23] = 0
    J[5][24] = 0
    J[5][25] = 0
    J[5][26] = 0
    J[5][27] = 0
    J[5][28] = 0
    J[5][29] = 0
    J[5][30] = 0
    J[5][31] = 0
    J[5][32] = 0.00104661*Cj
    J[6][0] = 0
    J[6][1] = 0
    J[6][2] = 0
    J[6][3] = 0
    J[6][4] = 0
    J[6][5] = 0
    J[6][6] = -0.0038442886*M146
    J[6][7] = 0
    J[6][8] = 0
    J[6][9] = 0.000330858*M163
    J[6][10] = 0
    J[6][11] = -0.0038442886*HelperAAk
    J[6][12] = 0
    J[6][13] = 0.000330858*M10
    J[6][14] = 0
    J[6][15] = 0
    J[6][16] = 0
    J[6][17] = 0
    J[6][18] = 0
    J[6][19] = 0
    J[6][20] = 0
    J[6][21] = 0
    J[6][22] = 0
    J[6][23] = 0
    J[6][24] = 0
    J[6][25] = 0
    J[6][26] = 0
    J[6][27] = 0
    J[6][28] = 0
    J[6][29] = 0
    J[6][30] = 0
    J[6][31] = 0
    J[6][32] = 0
    J[7][0] = 0
    J[7][1] = 0
    J[7][2] = 0
    J[7][3] = 0
    J[7][4] = 0
    J[7][5] = 0
    J[7][6] = 0
    J[7][7] = -0.0038442886*M75
    J[7][8] = 0
    J[7][9] = 0
    J[7][10] = 0
    J[7][11] = 0
    J[7][12] = 0
    J[7][13] = 0
    J[7][14] = 0
    J[7][15] = 0
    J[7][16] = 0
    J[7][17] = 0
    J[7][18] = 0
    J[7][19] = 0
    J[7][20] = 0
    J[7][21] = 0.000330858*M91
    J[7][22] = 0
    J[7][23] = -0.0038442886*HelperBBr
    J[7][24] = 0
    J[7][25] = 0
    J[7][26] = 0.000330858*M69
    J[7][27] = 0
    J[7][28] = 0
    J[7][29] = 0
    J[7][30] = 0
    J[7][31] = 0
    J[7][32] = 0
    J[8][0] = 0
    J[8][1] = 0
    J[8][2] = 0
    J[8][3] = 0
    J[8][4] = 0
    J[8][5] = 0
    J[8][6] = 0
    J[8][7] = 0
    J[8][8] = -0.0038442886*M112
    J[8][9] = 0
    J[8][10] = -0.0038442886*HelperCCj
    J[8][11] = 0
    J[8][12] = 0
    J[8][13] = 0
    J[8][14] = 0
    J[8][15] = 0.000330858*M56
    J[8][16] = 0
    J[8][17] = 0
    J[8][18] = 0
    J[8][19] = 0.000330858*M206
    J[8][20] = 0
    J[8][21] = 0
    J[8][22] = 0
    J[8][23] = 0
    J[8][24] = 0
    J[8][25] = 0
    J[8][26] = 0
    J[8][27] = 0
    J[8][28] = 0
    J[8][29] = 0
    J[8][30] = 0
    J[8][31] = 0
    J[8][32] = 0
    J[9][0] = 0.00104769*M146
    J[9][1] = 0
    J[9][2] = 0.0020865*M5
    J[9][3] = 0
    J[9][4] = 0
    J[9][5] = 0
    J[9][6] = 1.10286e-5*M146
    J[9][7] = 0
    J[9][8] = 0
    J[9][9] = -0.002089038*M163 - 0.00104769*ProduceCAkAk
    J[9][10] = 0
    J[9][11] = 0.00104769*Ak + 1.10286e-5*HelperAAk
    J[9][12] = 0
    J[9][13] = -0.002089038*M10
    J[9][14] = 0
    J[9][15] = 0
    J[9][16] = 0
    J[9][17] = 0.0020865*Cj
    J[9][18] = 0
    J[9][19] = 0
    J[9][20] = 0
    J[9][21] = 0
    J[9][22] = 0
    J[9][23] = 0
    J[9][24] = 0
    J[9][25] = 0
    J[9][26] = 0
    J[9][27] = 0
    J[9][28] = 0
    J[9][29] = -0.00104769*M10
    J[9][30] = 0
    J[9][31] = 0
    J[9][32] = 0
    J[10][0] = 0
    J[10][1] = 0
    J[10][2] = -0.00104769*M112
    J[10][3] = 0
    J[10][4] = 0
    J[10][5] = 0
    J[10][6] = 0
    J[10][7] = 0
    J[10][8] = -0.0038442886*M112
    J[10][9] = 0
    J[10][10] = -0.00104769*Cj - 0.0038442886*HelperCCj
    J[10][11] = 0
    J[10][12] = 0
    J[10][13] = 0
    J[10][14] = 0
    J[10][15] = 0.000330858*M56
    J[10][16] = 0
    J[10][17] = 0
    J[10][18] = 0
    J[10][19] = 0.000330858*M206 + 0.00104769*ProduceBCjCj
    J[10][20] = 0
    J[10][21] = 0
    J[10][22] = 0
    J[10][23] = 0
    J[10][24] = 0
    J[10][25] = 0
    J[10][26] = 0
    J[10][27] = 0
    J[10][28] = 0.00104769*M56
    J[10][29] = 0
    J[10][30] = 0
    J[10][31] = 0
    J[10][32] = 0
    J[11][0] = -0.00104769*M146
    J[11][1] = 0
    J[11][2] = 0
    J[11][3] = 0
    J[11][4] = 0
    J[11][5] = 0
    J[11][6] = -0.0038442886*M146
    J[11][7] = 0
    J[11][8] = 0
    J[11][9] = 0.000330858*M163 + 0.00104769*ProduceCAkAk
    J[11][10] = 0
    J[11][11] = -0.00104769*Ak - 0.0038442886*HelperAAk
    J[11][12] = 0
    J[11][13] = 0.000330858*M10
    J[11][14] = 0
    J[11][15] = 0
    J[11][16] = 0
    J[11][17] = 0
    J[11][18] = 0
    J[11][19] = 0
    J[11][20] = 0
    J[11][21] = 0
    J[11][22] = 0
    J[11][23] = 0
    J[11][24] = 0
    J[11][25] = 0
    J[11][26] = 0
    J[11][27] = 0
    J[11][28] = 0
    J[11][29] = 0.00104769*M10
    J[11][30] = 0
    J[11][31] = 0
    J[11][32] = 0
    J[12][0] = 0
    J[12][1] = 0
    J[12][2] = 0
    J[12][3] = 0
    J[12][4] = 0
    J[12][5] = 0
    J[12][6] = 0.00383326*M146
    J[12][7] = 0
    J[12][8] = 0
    J[12][9] = 0.00175818*M163
    J[12][10] = 0
    J[12][11] = 0.00383326*HelperAAk
    J[12][12] = 0
    J[12][13] = 0.00175818*M10
    J[12][14] = 0
    J[12][15] = 0
    J[12][16] = 0
    J[12][17] = 0
    J[12][18] = 0
    J[12][19] = 0
    J[12][20] = 0
    J[12][21] = 0
    J[12][22] = 0
    J[12][23] = 0
    J[12][24] = 0
    J[12][25] = 0
    J[12][26] = 0
    J[12][27] = 0
    J[12][28] = 0
    J[12][29] = 0
    J[12][30] = 0
    J[12][31] = 0
    J[12][32] = 0
    J[13][0] = 0
    J[13][1] = 0
    J[13][2] = 0
    J[13][3] = 0
    J[13][4] = 0
    J[13][5] = 0
    J[13][6] = 1.10286e-5*M146
    J[13][7] = 0
    J[13][8] = 0
    J[13][9] = -0.002089038*M163
    J[13][10] = 0
    J[13][11] = 1.10286e-5*HelperAAk
    J[13][12] = 0
    J[13][13] = -0.002089038*M10
    J[13][14] = 0
    J[13][15] = 0
    J[13][16] = 0
    J[13][17] = 0
    J[13][18] = 0
    J[13][19] = 0
    J[13][20] = 0
    J[13][21] = 0
    J[13][22] = 0
    J[13][23] = 0
    J[13][24] = 0
    J[13][25] = 0
    J[13][26] = 0
    J[13][27] = 0
    J[13][28] = 0
    J[13][29] = 0
    J[13][30] = 0
    J[13][31] = 0
    J[13][32] = 0
    J[14][0] = 0
    J[14][1] = 0
    J[14][2] = 0
    J[14][3] = 0
    J[14][4] = 0
    J[14][5] = 0
    J[14][6] = 0
    J[14][7] = 0
    J[14][8] = 0.00383326*M112
    J[14][9] = 0
    J[14][10] = 0.00383326*HelperCCj
    J[14][11] = 0
    J[14][12] = 0
    J[14][13] = 0
    J[14][14] = 0
    J[14][15] = 0.00175818*M56
    J[14][16] = 0
    J[14][17] = 0
    J[14][18] = 0
    J[14][19] = 0.00175818*M206
    J[14][20] = 0
    J[14][21] = 0
    J[14][22] = 0
    J[14][23] = 0
    J[14][24] = 0
    J[14][25] = 0
    J[14][26] = 0
    J[14][27] = 0
    J[14][28] = 0
    J[14][29] = 0
    J[14][30] = 0
    J[14][31] = 0
    J[14][32] = 0
    J[15][0] = 0
    J[15][1] = 0
    J[15][2] = 0
    J[15][3] = 0
    J[15][4] = 0
    J[15][5] = 0
    J[15][6] = 0
    J[15][7] = 0
    J[15][8] = 1.10286e-5*M112
    J[15][9] = 0
    J[15][10] = 1.10286e-5*HelperCCj
    J[15][11] = 0
    J[15][12] = 0
    J[15][13] = 0
    J[15][14] = 0
    J[15][15] = -0.002089038*M56
    J[15][16] = 0
    J[15][17] = 0
    J[15][18] = 0
    J[15][19] = -0.002089038*M206
    J[15][20] = 0
    J[15][21] = 0
    J[15][22] = 0
    J[15][23] = 0
    J[15][24] = 0
    J[15][25] = 0
    J[15][26] = 0
    J[15][27] = 0
    J[15][28] = 0
    J[15][29] = 0
    J[15][30] = 0
    J[15][31] = 0
    J[15][32] = 0
    J[16][0] = 0
    J[16][1] = -0.0020865*M30
    J[16][2] = 0.00104661*ReactCBCj
    J[16][3] = 0
    J[16][4] = 0
    J[16][5] = -0.00104661*M30
    J[16][6] = 0
    J[16][7] = 0
    J[16][8] = 0
    J[16][9] = 0
    J[16][10] = 0
    J[16][11] = 0
    J[16][12] = 0
    J[16][13] = 0
    J[16][14] = 0
    J[16][15] = 0
    J[16][16] = -0.00104661*BackCB - 0.0020865*Br
    J[16][17] = 0
    J[16][18] = 0
    J[16][19] = 0
    J[16][20] = 0
    J[16][21] = 0
    J[16][22] = 0
    J[16][23] = 0
    J[16][24] = 0
    J[16][25] = 0
    J[16][26] = 0
    J[16][27] = 0
    J[16][28] = 0
    J[16][29] = 0
    J[16][30] = 0
    J[16][31] = 0
    J[16][32] = 0.00104661*Cj
    J[17][0] = 0.00104661*ReactACAk
    J[17][1] = 0
    J[17][2] = -0.0020865*M5
    J[17][3] = -0.00104661*M5
    J[17][4] = 0
    J[17][5] = 0
    J[17][6] = 0
    J[17][7] = 0
    J[17][8] = 0
    J[17][9] = 0
    J[17][10] = 0
    J[17][11] = 0
    J[17][12] = 0
    J[17][13] = 0
    J[17][14] = 0
    J[17][15] = 0
    J[17][16] = 0
    J[17][17] = -0.00104661*BackAC - 0.0020865*Cj
    J[17][18] = 0
    J[17][19] = 0
    J[17][20] = 0
    J[17][21] = 0
    J[17][22] = 0
    J[17][23] = 0
    J[17][24] = 0
    J[17][25] = 0
    J[17][26] = 0
    J[17][27] = 0
    J[17][28] = 0
    J[17][29] = 0
    J[17][30] = 0.00104661*Ak
    J[17][31] = 0
    J[17][32] = 0
    J[18][0] = 0
    J[18][1] = 0.0020865*M30
    J[18][2] = 0
    J[18][3] = 0
    J[18][4] = 0
    J[18][5] = 0
    J[18][6] = 0
    J[18][7] = 0
    J[18][8] = 0
    J[18][9] = 0
    J[18][10] = 0
    J[18][11] = 0
    J[18][12] = 0
    J[18][13] = 0
    J[18][14] = 0
    J[18][15] = 0
    J[18][16] = 0.0020865*Br
    J[18][17] = 0
    J[18][18] = 0
    J[18][19] = 0
    J[18][20] = 0
    J[18][21] = 0
    J[18][22] = 0
    J[18][23] = 0
    J[18][24] = 0
    J[18][25] = 0
    J[18][26] = 0
    J[18][27] = 0
    J[18][28] = 0
    J[18][29] = 0
    J[18][30] = 0
    J[18][31] = 0
    J[18][32] = 0
    J[19][0] = 0
    J[19][1] = 0.0020865*M30
    J[19][2] = 0.00104769*M112
    J[19][3] = 0
    J[19][4] = 0
    J[19][5] = 0
    J[19][6] = 0
    J[19][7] = 0
    J[19][8] = 1.10286e-5*M112
    J[19][9] = 0
    J[19][10] = 0.00104769*Cj + 1.10286e-5*HelperCCj
    J[19][11] = 0
    J[19][12] = 0
    J[19][13] = 0
    J[19][14] = 0
    J[19][15] = -0.002089038*M56
    J[19][16] = 0.0020865*Br
    J[19][17] = 0
    J[19][18] = 0
    J[19][19] = -0.002089038*M206 - 0.00104769*ProduceBCjCj
    J[19][20] = 0
    J[19][21] = 0
    J[19][22] = 0
    J[19][23] = 0
    J[19][24] = 0
    J[19][25] = 0
    J[19][26] = 0
    J[19][27] = 0
    J[19][28] = -0.00104769*M56
    J[19][29] = 0
    J[19][30] = 0
    J[19][31] = 0
    J[19][32] = 0
    J[20][0] = -0.0020865*M60
    J[20][1] = 0.00104661*ReactBABr
    J[20][2] = 0
    J[20][3] = 0
    J[20][4] = -0.00104661*M60
    J[20][5] = 0
    J[20][6] = 0
    J[20][7] = 0
    J[20][8] = 0
    J[20][9] = 0
    J[20][10] = 0
    J[20][11] = 0
    J[20][12] = 0
    J[20][13] = 0
    J[20][14] = 0
    J[20][15] = 0
    J[20][16] = 0
    J[20][17] = 0
    J[20][18] = 0
    J[20][19] = 0
    J[20][20] = -0.0020865*Ak - 0.00104661*BackBA
    J[20][21] = 0
    J[20][22] = 0
    J[20][23] = 0
    J[20][24] = 0
    J[20][25] = 0
    J[20][26] = 0
    J[20][27] = 0
    J[20][28] = 0
    J[20][29] = 0
    J[20][30] = 0
    J[20][31] = 0.00104661*Br
    J[20][32] = 0
    J[21][0] = 0.0020865*M60
    J[21][1] = 0.00104769*M75
    J[21][2] = 0
    J[21][3] = 0
    J[21][4] = 0
    J[21][5] = 0
    J[21][6] = 0
    J[21][7] = 1.10286e-5*M75
    J[21][8] = 0
    J[21][9] = 0
    J[21][10] = 0
    J[21][11] = 0
    J[21][12] = 0
    J[21][13] = 0
    J[21][14] = 0
    J[21][15] = 0
    J[21][16] = 0
    J[21][17] = 0
    J[21][18] = 0
    J[21][19] = 0
    J[21][20] = 0.0020865*Ak
    J[21][21] = -0.002089038*M91 - 0.00104769*ProduceABrBr
    J[21][22] = 0
    J[21][23] = 0.00104769*Br + 1.10286e-5*HelperBBr
    J[21][24] = 0
    J[21][25] = 0
    J[21][26] = -0.002089038*M69
    J[21][27] = -0.00104769*M69
    J[21][28] = 0
    J[21][29] = 0
    J[21][30] = 0
    J[21][31] = 0
    J[21][32] = 0
    J[22][0] = 0.0020865*M60
    J[22][1] = 0
    J[22][2] = 0
    J[22][3] = 0
    J[22][4] = 0
    J[22][5] = 0
    J[22][6] = 0
    J[22][7] = 0
    J[22][8] = 0
    J[22][9] = 0
    J[22][10] = 0
    J[22][11] = 0
    J[22][12] = 0
    J[22][13] = 0
    J[22][14] = 0
    J[22][15] = 0
    J[22][16] = 0
    J[22][17] = 0
    J[22][18] = 0
    J[22][19] = 0
    J[22][20] = 0.0020865*Ak
    J[22][21] = 0
    J[22][22] = 0
    J[22][23] = 0
    J[22][24] = 0
    J[22][25] = 0
    J[22][26] = 0
    J[22][27] = 0
    J[22][28] = 0
    J[22][29] = 0
    J[22][30] = 0
    J[22][31] = 0
    J[22][32] = 0
    J[23][0] = 0
    J[23][1] = -0.00104769*M75
    J[23][2] = 0
    J[23][3] = 0
    J[23][4] = 0
    J[23][5] = 0
    J[23][6] = 0
    J[23][7] = -0.0038442886*M75
    J[23][8] = 0
    J[23][9] = 0
    J[23][10] = 0
    J[23][11] = 0
    J[23][12] = 0
    J[23][13] = 0
    J[23][14] = 0
    J[23][15] = 0
    J[23][16] = 0
    J[23][17] = 0
    J[23][18] = 0
    J[23][19] = 0
    J[23][20] = 0
    J[23][21] = 0.000330858*M91 + 0.00104769*ProduceABrBr
    J[23][22] = 0
    J[23][23] = -0.00104769*Br - 0.0038442886*HelperBBr
    J[23][24] = 0
    J[23][25] = 0
    J[23][26] = 0.000330858*M69
    J[23][27] = 0.00104769*M69
    J[23][28] = 0
    J[23][29] = 0
    J[23][30] = 0
    J[23][31] = 0
    J[23][32] = 0
    J[24][0] = 0
    J[24][1] = 0
    J[24][2] = 0
    J[24][3] = 0
    J[24][4] = 0
    J[24][5] = 0
    J[24][6] = 0
    J[24][7] = 0.00383326*M75
    J[24][8] = 0
    J[24][9] = 0
    J[24][10] = 0
    J[24][11] = 0
    J[24][12] = 0
    J[24][13] = 0
    J[24][14] = 0
    J[24][15] = 0
    J[24][16] = 0
    J[24][17] = 0
    J[24][18] = 0
    J[24][19] = 0
    J[24][20] = 0
    J[24][21] = 0.00175818*M91
    J[24][22] = 0
    J[24][23] = 0.00383326*HelperBBr
    J[24][24] = 0
    J[24][25] = 0
    J[24][26] = 0.00175818*M69
    J[24][27] = 0
    J[24][28] = 0
    J[24][29] = 0
    J[24][30] = 0
    J[24][31] = 0
    J[24][32] = 0
    J[25][0] = 0
    J[25][1] = 0
    J[25][2] = 0.0020865*M5
    J[25][3] = 0
    J[25][4] = 0
    J[25][5] = 0
    J[25][6] = 0
    J[25][7] = 0
    J[25][8] = 0
    J[25][9] = 0
    J[25][10] = 0
    J[25][11] = 0
    J[25][12] = 0
    J[25][13] = 0
    J[25][14] = 0
    J[25][15] = 0
    J[25][16] = 0
    J[25][17] = 0.0020865*Cj
    J[25][18] = 0
    J[25][19] = 0
    J[25][20] = 0
    J[25][21] = 0
    J[25][22] = 0
    J[25][23] = 0
    J[25][24] = 0
    J[25][25] = 0
    J[25][26] = 0
    J[25][27] = 0
    J[25][28] = 0
    J[25][29] = 0
    J[25][30] = 0
    J[25][31] = 0
    J[25][32] = 0
    J[26][0] = 0
    J[26][1] = 0
    J[26][2] = 0
    J[26][3] = 0
    J[26][4] = 0
    J[26][5] = 0
    J[26][6] = 0
    J[26][7] = 1.10286e-5*M75
    J[26][8] = 0
    J[26][9] = 0
    J[26][10] = 0
    J[26][11] = 0
    J[26][12] = 0
    J[26][13] = 0
    J[26][14] = 0
    J[26][15] = 0
    J[26][16] = 0
    J[26][17] = 0
    J[26][18] = 0
    J[26][19] = 0
    J[26][20] = 0
    J[26][21] = -0.002089038*M91
    J[26][22] = 0
    J[26][23] = 1.10286e-5*HelperBBr
    J[26][24] = 0
    J[26][25] = 0
    J[26][26] = -0.002089038*M69
    J[26][27] = 0
    J[26][28] = 0
    J[26][29] = 0
    J[26][30] = 0
    J[26][31] = 0
    J[26][32] = 0
    J[27][0] = 0
    J[27][1] = 0.00104769*M75
    J[27][2] = 0
    J[27][3] = 0
    J[27][4] = 0
    J[27][5] = 0
    J[27][6] = 0
    J[27][7] = 0
    J[27][8] = 0
    J[27][9] = 0
    J[27][10] = 0
    J[27][11] = 0
    J[27][12] = 0
    J[27][13] = 0
    J[27][14] = 0
    J[27][15] = 0
    J[27][16] = 0
    J[27][17] = 0
    J[27][18] = 0
    J[27][19] = 0
    J[27][20] = 0
    J[27][21] = -0.00104769*ProduceABrBr
    J[27][22] = 0
    J[27][23] = 0.00104769*Br
    J[27][24] = 0
    J[27][25] = 0
    J[27][26] = 0
    J[27][27] = -0.00104769*M69
    J[27][28] = 0
    J[27][29] = 0
    J[27][30] = 0
    J[27][31] = 0
    J[27][32] = 0
    J[28][0] = 0
    J[28][1] = 0
    J[28][2] = 0.00104769*M112
    J[28][3] = 0
    J[28][4] = 0
    J[28][5] = 0
    J[28][6] = 0
    J[28][7] = 0
    J[28][8] = 0
    J[28][9] = 0
    J[28][10] = 0.00104769*Cj
    J[28][11] = 0
    J[28][12] = 0
    J[28][13] = 0
    J[28][14] = 0
    J[28][15] = 0
    J[28][16] = 0
    J[28][17] = 0
    J[28][18] = 0
    J[28][19] = -0.00104769*ProduceBCjCj
    J[28][20] = 0
    J[28][21] = 0
    J[28][22] = 0
    J[28][23] = 0
    J[28][24] = 0
    J[28][25] = 0
    J[28][26] = 0
    J[28][27] = 0
    J[28][28] = -0.00104769*M56
    J[28][29] = 0
    J[28][30] = 0
    J[28][31] = 0
    J[28][32] = 0
    J[29][0] = 0.00104769*M146
    J[29][1] = 0
    J[29][2] = 0
    J[29][3] = 0
    J[29][4] = 0
    J[29][5] = 0
    J[29][6] = 0
    J[29][7] = 0
    J[29][8] = 0
    J[29][9] = -0.00104769*ProduceCAkAk
    J[29][10] = 0
    J[29][11] = 0.00104769*Ak
    J[29][12] = 0
    J[29][13] = 0
    J[29][14] = 0
    J[29][15] = 0
    J[29][16] = 0
    J[29][17] = 0
    J[29][18] = 0
    J[29][19] = 0
    J[29][20] = 0
    J[29][21] = 0
    J[29][22] = 0
    J[29][23] = 0
    J[29][24] = 0
    J[29][25] = 0
    J[29][26] = 0
    J[29][27] = 0
    J[29][28] = 0
    J[29][29] = -0.00104769*M10
    J[29][30] = 0
    J[29][31] = 0
    J[29][32] = 0
    J[30][0] = -0.00104661*ReactACAk
    J[30][1] = 0
    J[30][2] = 0
    J[30][3] = 0.00104661*M5
    J[30][4] = 0
    J[30][5] = 0
    J[30][6] = 0
    J[30][7] = 0
    J[30][8] = 0
    J[30][9] = 0
    J[30][10] = 0
    J[30][11] = 0
    J[30][12] = 0
    J[30][13] = 0
    J[30][14] = 0
    J[30][15] = 0
    J[30][16] = 0
    J[30][17] = 0.00104661*BackAC
    J[30][18] = 0
    J[30][19] = 0
    J[30][20] = 0
    J[30][21] = 0
    J[30][22] = 0
    J[30][23] = 0
    J[30][24] = 0
    J[30][25] = 0
    J[30][26] = 0
    J[30][27] = 0
    J[30][28] = 0
    J[30][29] = 0
    J[30][30] = -0.00104661*Ak
    J[30][31] = 0
    J[30][32] = 0
    J[31][0] = 0
    J[31][1] = -0.00104661*ReactBABr
    J[31][2] = 0
    J[31][3] = 0
    J[31][4] = 0.00104661*M60
    J[31][5] = 0
    J[31][6] = 0
    J[31][7] = 0
    J[31][8] = 0
    J[31][9] = 0
    J[31][10] = 0
    J[31][11] = 0
    J[31][12] = 0
    J[31][13] = 0
    J[31][14] = 0
    J[31][15] = 0
    J[31][16] = 0
    J[31][17] = 0
    J[31][18] = 0
    J[31][19] = 0
    J[31][20] = 0.00104661*BackBA
    J[31][21] = 0
    J[31][22] = 0
    J[31][23] = 0
    J[31][24] = 0
    J[31][25] = 0
    J[31][26] = 0
    J[31][27] = 0
    J[31][28] = 0
    J[31][29] = 0
    J[31][30] = 0
    J[31][31] = -0.00104661*Br
    J[31][32] = 0
    J[32][0] = 0
    J[32][1] = 0
    J[32][2] = -0.00104661*ReactCBCj
    J[32][3] = 0
    J[32][4] = 0
    J[32][5] = 0.00104661*M30
    J[32][6] = 0
    J[32][7] = 0
    J[32][8] = 0
    J[32][9] = 0
    J[32][10] = 0
    J[32][11] = 0
    J[32][12] = 0
    J[32][13] = 0
    J[32][14] = 0
    J[32][15] = 0
    J[32][16] = 0.00104661*BackCB
    J[32][17] = 0
    J[32][18] = 0
    J[32][19] = 0
    J[32][20] = 0
    J[32][21] = 0
    J[32][22] = 0
    J[32][23] = 0
    J[32][24] = 0
    J[32][25] = 0
    J[32][26] = 0
    J[32][27] = 0
    J[32][28] = 0
    J[32][29] = 0
    J[32][30] = 0
    J[32][31] = 0
    J[32][32] = -0.00104661*Cj
    return J


def add_integrator_args(parser):
    """ODE integration aruments."""
    solver = parser.add_argument_group('odeint parameters')
    plotter = parser.add_argument_group('plotting parameters')

    # required: simulation time and output settings
    solver.add_argument("--t0", type=float, default=0, metavar='<flt>',
            help="First time point of the time-course.")
    solver.add_argument("--t8", type=float, default=100, metavar='<flt>',
            help="End point of simulation time.")
    plotter.add_argument("--t-lin", type=int, default=500, metavar='<int>',
            help="Returns --t-lin evenly spaced numbers on a linear scale from --t0 to --t8.")
    plotter.add_argument("--t-log", type=int, default=None, metavar='<int>',
            help="Returns --t-log evenly spaced numbers on a logarithmic scale from --t0 to --t8.")

    # required: initial concentration vector
    solver.add_argument("--p0", nargs='+', metavar='<int/str>=<flt>',
            help="""Vector of initial species concentrations. 
            E.g. \"--p0 1=0.5 3=0.7\" stands for 1st species at a concentration of 0.5 
            and 3rd species at a concentration of 0.7. You may chose to address species
            directly by name, e.g.: --p0 C=0.5.""")
    # advanced: scipy.integrate.odeint parameters
    solver.add_argument("-a", "--atol", type=float, default=None, metavar='<flt>',
            help="Specify absolute tolerance for the solver.")
    solver.add_argument("-r", "--rtol", type=float, default=None, metavar='<flt>',
            help="Specify relative tolerance for the solver.")
    solver.add_argument("--mxstep", type=int, default=0, metavar='<int>',
            help="Maximum number of steps allowed for each integration point in t.")

    # optional: choose output formats
    plotter.add_argument("--list-labels", action='store_true',
            help="Print all species and exit.")
    plotter.add_argument("--labels", nargs='+', default=[], metavar='<str>+',
            help="""Specify the (order of) species which should appear in the pyplot legend, 
            as well as the order of species for nxy output format.""")
    plotter.add_argument("--labels-strict", action='store_true',
            help="""When using pyplot, only plot tracjectories corresponding to labels,
            when using nxy, only print the trajectories corresponding to labels.""")
 
    plotter.add_argument("--nxy", action='store_true',
            help="Print time course to STDOUT in nxy format.")
    plotter.add_argument("--header", action='store_true',
            help="Print header for trajectories.")

    plotter.add_argument("--pyplot", default='', metavar='<str>',
            help="Specify a filename to plot the ODE simulation.")
    plotter.add_argument("--pyplot-xlim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the x-axis.")
    plotter.add_argument("--pyplot-ylim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the y-axis.")
    plotter.add_argument("--pyplot-labels", nargs='+', default=[], metavar='<str>+',
            help=argparse.SUPPRESS)
    return

def flint(inp):
    return int(float(inp)) if float(inp) == int(float(inp)) else float(inp)

def set_logger(verbose, logfile):
    # ~~~~~~~~~~~~~
    # Logging Setup 
    # ~~~~~~~~~~~~~
    logger.setLevel(logging.DEBUG)
    handler = logging.FileHandler(logfile) if logfile else logging.StreamHandler()
    if verbose == 0:
        handler.setLevel(logging.WARNING)
    elif verbose == 1:
        handler.setLevel(logging.INFO)
    elif verbose == 2:
        handler.setLevel(logging.DEBUG)
    elif verbose >= 3:
        handler.setLevel(logging.NOTSET)
    formatter = logging.Formatter('%(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)


def integrate(args, setlogger = False):
    """Main interface to solve the ODE-system.

    Args:
      args (:obj:`argparse.ArgumentParser()`): An argparse object containing all of
        the arguments of :obj:`crnsimulator.add_integrator_args()`.

    Prints:
      - plot files
      - time-course

    Returns:
      Nothing
    """
    if setlogger:
        set_logger(args.verbose, args.logfile)

    if args.pyplot_labels:
        logger.warning('Deprecated argument: --pyplot_labels.')

    svars = ["Ak", "Br", "Cj", "BackAC", "BackBA", "BackCB", "HelperAAk", "HelperBBr", "HelperCCj", "M10", "M112", "M146", "M160", "M163", "M203", "M206", "M30", "M5", "M55", "M56", "M60", "M69", "M70", "M75", "M87", "M9", "M91", "ProduceABrBr", "ProduceBCjCj", "ProduceCAkAk", "ReactACAk", "ReactBABr", "ReactCBCj"]

    p0 = [0] * len(svars)
    p0[0] = 110.0
    p0[1] = 100.0
    p0[2] = 30.000000000000004
    p0[3] = 1000.0000000000001
    p0[4] = 1000.0000000000001
    p0[5] = 1000.0000000000001
    p0[6] = 750.0
    p0[7] = 750.0
    p0[8] = 750.0
    p0[27] = 1000.0000000000001
    p0[28] = 1000.0000000000001
    p0[29] = 1000.0000000000001
    p0[30] = 1000.0000000000001
    p0[31] = 1000.0000000000001
    p0[32] = 1000.0000000000001
    
    const = None
    #<&>CONSTANT_SPECIES_INFO<&>#
    if args.p0:
        for term in args.p0:
            p, o = term.split('=')
            try:
                pi = svars.index(p)
            except ValueError as e:
                pi = int(p) - 1
            finally:
                p0[pi] = flint(o)
    else:
        msg = 'Specify a vector of initial concentrations: ' + \
                'e.g. --p0 1=0.1 2=0.005 3=1e-6 (see --help)'
        if sum(p0) == 0:
            logger.warning(msg)
            args.list_labels = True
        else:
            logger.info(msg)

    if args.list_labels:
        print('List of variables and initial concentrations:')
        for e, v in enumerate(svars, 1):
            if args.labels_strict and e > len(args.labels):
                break
            print(f'{e} {v} {p0[e-1]} {"constant" if const and const[e-1] else ""}')
        raise SystemExit('Initial concentrations can be overwritten by --p0 argument')

    if not args.nxy and not args.pyplot:
        logger.warning('Use --pyplot and/or --nxy to plot your results.')

    if not args.t8:
        raise ODETemplateError('Specify a valid end-time for the simulation: --t8 <flt>')

    if args.t_log:
        if args.t0 == 0:
            raise ODETemplateError('--t0 cannot be 0 when using log-scale!')
        time = np.logspace(np.log10(args.t0), np.log10(args.t8), num=args.t_log)
    elif args.t_lin:
        time = np.linspace(args.t0, args.t8, num=args.t_lin)
    else:
        raise ODETemplateError('Please specify either --t-lin or --t-log. (see --help)')

    # It would be nice if it is possible to read alternative rates from a file instead.
    # None triggers the default-rates that are hard-coded in the (this) library file.
    rates = None

    logger.info(f'Initial concentrations: {list(zip(svars, p0))}')
    # TODO: logging should report more info on parameters.

    ny = odeint(odesystem,
        np.array(p0), time, (rates, ), Dfun = jacobian,
        atol=args.atol, rtol=args.rtol, mxstep=args.mxstep).T

    # Output
    if args.nxy and args.labels_strict:
        end = len(args.labels)
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars[:end]]))
        for i in zip(time, *ny[:end]):
            print(' '.join(map("{:.9e}".format, i)))
    elif args.nxy:
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars]))
        for i in zip(time, *ny):
            print(' '.join(map("{:.9e}".format, i)))

    if args.pyplot:
        from crnsimulator.plotting import ode_plotter
        plotfile = ode_plotter(args.pyplot, time, ny, svars,
                               log=True if args.t_log else False,
                               labels=set(args.labels),
                               xlim = args.pyplot_xlim,
                               ylim = args.pyplot_ylim,
                               labels_strict = args.labels_strict)
        logger.info(f"Plotting successfull. Wrote plot to file: {plotfile}")

    return zip(time, *ny)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v", "--verbose", action='count', default = 0,
        help = "Print logging output. (-vv increases verbosity.)")
    parser.add_argument('--logfile', default = '', action = 'store', metavar = '<str>',
        help = """Redirect logging information to a file.""")
    add_integrator_args(parser)
    args = parser.parse_args()
    integrate(args, setlogger = True)

