#!/usr/bin/env python
"""
A template file to simulate a specific system of Ordinary Differential Equations (ODEs).

... or an autogenerated script from the *crnsimulator* Python package.

Note: If this file is executable, it is *autogenerated*.
    This means it contains a system of hardcoded ODEs together with some
    default parameters. While it may be tempting to tweak some functions,
    beware that this file may be overwritten by the next execution of the
    `crnsimulator` executable.  Edits should be done at the source file:
    "crnsimulator.odelib_template.py" or you can provide an alternative
    template file. Use the option --output to avoid overwriting this file.

Usage: 
    python odesystem.py --help
"""

import logging
logger = logging.getLogger(__name__)

import argparse
import numpy as np
from scipy.integrate import odeint

class ODETemplateError(Exception):
    pass

rates = {
    
}

def odesystem(p0, t0, r):
    Cj, Ck, shCj, shCk, BackBC, HelperB, HelperCCk, ProduceBCjCk, ReactCBCj, U12, U19, U20, U30, U41, U52, U8, US10, US22, US23, US25, US37, US45, US5, shBackBC, shHelperB, shHelperCCk, shProduceBCjCk, shReactCBCj = p0
    if not r : r = rates


    dCjdt = 1.0e-5*BackBC*U12 - 8.0e-6*Cj*ReactCBCj - 1.0e-5*Cj*U41 + 1.0e-5*ProduceBCjCk*U19
    dCkdt = 1.0e-5*BackBC*U8 - 8.0e-6*Ck*ReactCBCj + 2.0e-8*HelperCCk*ProduceBCjCk + 1.0e-5*HelperCCk*U41
    dshCjdt = 0.001*US22*shProduceBCjCk - 0.001*US37*shCj + 0.001*US5*shBackBC - 0.0008*shCj*shReactCBCj
    dshCkdt = 0.001*US10*shBackBC + 0.001*US37*shHelperCCk - 0.0008*shCk*shReactCBCj + 2.0e-8*shHelperCCk*shProduceBCjCk
    dBackBCdt = -1.0e-5*BackBC*U12 - 1.0e-5*BackBC*U8 + 8.0e-6*Cj*ReactCBCj + 8.0e-6*Ck*ReactCBCj
    dHelperBdt = -1.0e-5*HelperB*U12 - 1.0e-5*HelperB*U8
    dHelperCCkdt = -2.0e-8*HelperCCk*ProduceBCjCk - 1.0e-5*HelperCCk*U41
    dProduceBCjCkdt = 1.0e-5*Cj*U41 - 2.0e-8*HelperCCk*ProduceBCjCk - 1.0e-5*ProduceBCjCk*U19
    dReactCBCjdt = 1.0e-5*BackBC*U12 + 1.0e-5*BackBC*U8 - 8.0e-6*Cj*ReactCBCj - 8.0e-6*Ck*ReactCBCj
    dU12dt = -1.0e-5*BackBC*U12 + 8.0e-6*Cj*ReactCBCj - 1.0e-5*HelperB*U12
    dU19dt = 1.0e-5*Cj*U41 + 1.0e-5*HelperB*U12 + 1.0e-5*HelperB*U8 - 1.0e-5*ProduceBCjCk*U19
    dU20dt = 1.0e-5*HelperB*U12
    dU30dt = 1.0e-5*HelperB*U8
    dU41dt = -1.0e-5*Cj*U41 - 1.0e-5*HelperCCk*U41 + 1.0e-5*ProduceBCjCk*U19
    dU52dt = 1.0e-5*HelperCCk*U41
    dU8dt = -1.0e-5*BackBC*U8 + 8.0e-6*Ck*ReactCBCj - 1.0e-5*HelperB*U8
    dUS10dt = -0.001*US10*shBackBC - 0.001*US10*shHelperB + 0.0008*shCk*shReactCBCj
    dUS22dt = 0.001*US10*shHelperB - 0.001*US22*shProduceBCjCk + 0.001*US37*shCj + 0.001*US5*shHelperB
    dUS23dt = 0.001*US10*shHelperB
    dUS25dt = 0.001*US5*shHelperB
    dUS37dt = 0.001*US22*shProduceBCjCk - 0.001*US37*shCj - 0.001*US37*shHelperCCk
    dUS45dt = 0.001*US37*shHelperCCk
    dUS5dt = -0.001*US5*shBackBC - 0.001*US5*shHelperB + 0.0008*shCj*shReactCBCj
    dshBackBCdt = -0.001*US10*shBackBC - 0.001*US5*shBackBC + 0.0008*shCj*shReactCBCj + 0.0008*shCk*shReactCBCj
    dshHelperBdt = -0.001*US10*shHelperB - 0.001*US5*shHelperB
    dshHelperCCkdt = -0.001*US37*shHelperCCk - 2.0e-8*shHelperCCk*shProduceBCjCk
    dshProduceBCjCkdt = -0.001*US22*shProduceBCjCk + 0.001*US37*shCj - 2.0e-8*shHelperCCk*shProduceBCjCk
    dshReactCBCjdt = 0.001*US10*shBackBC + 0.001*US5*shBackBC - 0.0008*shCj*shReactCBCj - 0.0008*shCk*shReactCBCj
    return np.array([dCjdt, dCkdt, dshCjdt, dshCkdt, dBackBCdt, dHelperBdt, dHelperCCkdt, dProduceBCjCkdt, dReactCBCjdt, dU12dt, dU19dt, dU20dt, dU30dt, dU41dt, dU52dt, dU8dt, dUS10dt, dUS22dt, dUS23dt, dUS25dt, dUS37dt, dUS45dt, dUS5dt, dshBackBCdt, dshHelperBdt, dshHelperCCkdt, dshProduceBCjCkdt, dshReactCBCjdt])

def jacobian(p0, t0, r):
    Cj, Ck, shCj, shCk, BackBC, HelperB, HelperCCk, ProduceBCjCk, ReactCBCj, U12, U19, U20, U30, U41, U52, U8, US10, US22, US23, US25, US37, US45, US5, shBackBC, shHelperB, shHelperCCk, shProduceBCjCk, shReactCBCj = p0
    if not r : r = rates


    J = [[[] for i in range(len(p0))] for j in range(len(p0))]
    J[0][0] = -8.0e-6*ReactCBCj - 1.0e-5*U41
    J[0][1] = 0
    J[0][2] = 0
    J[0][3] = 0
    J[0][4] = 1.0e-5*U12
    J[0][5] = 0
    J[0][6] = 0
    J[0][7] = 1.0e-5*U19
    J[0][8] = -8.0e-6*Cj
    J[0][9] = 1.0e-5*BackBC
    J[0][10] = 1.0e-5*ProduceBCjCk
    J[0][11] = 0
    J[0][12] = 0
    J[0][13] = -1.0e-5*Cj
    J[0][14] = 0
    J[0][15] = 0
    J[0][16] = 0
    J[0][17] = 0
    J[0][18] = 0
    J[0][19] = 0
    J[0][20] = 0
    J[0][21] = 0
    J[0][22] = 0
    J[0][23] = 0
    J[0][24] = 0
    J[0][25] = 0
    J[0][26] = 0
    J[0][27] = 0
    J[1][0] = 0
    J[1][1] = -8.0e-6*ReactCBCj
    J[1][2] = 0
    J[1][3] = 0
    J[1][4] = 1.0e-5*U8
    J[1][5] = 0
    J[1][6] = 2.0e-8*ProduceBCjCk + 1.0e-5*U41
    J[1][7] = 2.0e-8*HelperCCk
    J[1][8] = -8.0e-6*Ck
    J[1][9] = 0
    J[1][10] = 0
    J[1][11] = 0
    J[1][12] = 0
    J[1][13] = 1.0e-5*HelperCCk
    J[1][14] = 0
    J[1][15] = 1.0e-5*BackBC
    J[1][16] = 0
    J[1][17] = 0
    J[1][18] = 0
    J[1][19] = 0
    J[1][20] = 0
    J[1][21] = 0
    J[1][22] = 0
    J[1][23] = 0
    J[1][24] = 0
    J[1][25] = 0
    J[1][26] = 0
    J[1][27] = 0
    J[2][0] = 0
    J[2][1] = 0
    J[2][2] = -0.001*US37 - 0.0008*shReactCBCj
    J[2][3] = 0
    J[2][4] = 0
    J[2][5] = 0
    J[2][6] = 0
    J[2][7] = 0
    J[2][8] = 0
    J[2][9] = 0
    J[2][10] = 0
    J[2][11] = 0
    J[2][12] = 0
    J[2][13] = 0
    J[2][14] = 0
    J[2][15] = 0
    J[2][16] = 0
    J[2][17] = 0.001*shProduceBCjCk
    J[2][18] = 0
    J[2][19] = 0
    J[2][20] = -0.001*shCj
    J[2][21] = 0
    J[2][22] = 0.001*shBackBC
    J[2][23] = 0.001*US5
    J[2][24] = 0
    J[2][25] = 0
    J[2][26] = 0.001*US22
    J[2][27] = -0.0008*shCj
    J[3][0] = 0
    J[3][1] = 0
    J[3][2] = 0
    J[3][3] = -0.0008*shReactCBCj
    J[3][4] = 0
    J[3][5] = 0
    J[3][6] = 0
    J[3][7] = 0
    J[3][8] = 0
    J[3][9] = 0
    J[3][10] = 0
    J[3][11] = 0
    J[3][12] = 0
    J[3][13] = 0
    J[3][14] = 0
    J[3][15] = 0
    J[3][16] = 0.001*shBackBC
    J[3][17] = 0
    J[3][18] = 0
    J[3][19] = 0
    J[3][20] = 0.001*shHelperCCk
    J[3][21] = 0
    J[3][22] = 0
    J[3][23] = 0.001*US10
    J[3][24] = 0
    J[3][25] = 0.001*US37 + 2.0e-8*shProduceBCjCk
    J[3][26] = 2.0e-8*shHelperCCk
    J[3][27] = -0.0008*shCk
    J[4][0] = 8.0e-6*ReactCBCj
    J[4][1] = 8.0e-6*ReactCBCj
    J[4][2] = 0
    J[4][3] = 0
    J[4][4] = -1.0e-5*U12 - 1.0e-5*U8
    J[4][5] = 0
    J[4][6] = 0
    J[4][7] = 0
    J[4][8] = 8.0e-6*Cj + 8.0e-6*Ck
    J[4][9] = -1.0e-5*BackBC
    J[4][10] = 0
    J[4][11] = 0
    J[4][12] = 0
    J[4][13] = 0
    J[4][14] = 0
    J[4][15] = -1.0e-5*BackBC
    J[4][16] = 0
    J[4][17] = 0
    J[4][18] = 0
    J[4][19] = 0
    J[4][20] = 0
    J[4][21] = 0
    J[4][22] = 0
    J[4][23] = 0
    J[4][24] = 0
    J[4][25] = 0
    J[4][26] = 0
    J[4][27] = 0
    J[5][0] = 0
    J[5][1] = 0
    J[5][2] = 0
    J[5][3] = 0
    J[5][4] = 0
    J[5][5] = -1.0e-5*U12 - 1.0e-5*U8
    J[5][6] = 0
    J[5][7] = 0
    J[5][8] = 0
    J[5][9] = -1.0e-5*HelperB
    J[5][10] = 0
    J[5][11] = 0
    J[5][12] = 0
    J[5][13] = 0
    J[5][14] = 0
    J[5][15] = -1.0e-5*HelperB
    J[5][16] = 0
    J[5][17] = 0
    J[5][18] = 0
    J[5][19] = 0
    J[5][20] = 0
    J[5][21] = 0
    J[5][22] = 0
    J[5][23] = 0
    J[5][24] = 0
    J[5][25] = 0
    J[5][26] = 0
    J[5][27] = 0
    J[6][0] = 0
    J[6][1] = 0
    J[6][2] = 0
    J[6][3] = 0
    J[6][4] = 0
    J[6][5] = 0
    J[6][6] = -2.0e-8*ProduceBCjCk - 1.0e-5*U41
    J[6][7] = -2.0e-8*HelperCCk
    J[6][8] = 0
    J[6][9] = 0
    J[6][10] = 0
    J[6][11] = 0
    J[6][12] = 0
    J[6][13] = -1.0e-5*HelperCCk
    J[6][14] = 0
    J[6][15] = 0
    J[6][16] = 0
    J[6][17] = 0
    J[6][18] = 0
    J[6][19] = 0
    J[6][20] = 0
    J[6][21] = 0
    J[6][22] = 0
    J[6][23] = 0
    J[6][24] = 0
    J[6][25] = 0
    J[6][26] = 0
    J[6][27] = 0
    J[7][0] = 1.0e-5*U41
    J[7][1] = 0
    J[7][2] = 0
    J[7][3] = 0
    J[7][4] = 0
    J[7][5] = 0
    J[7][6] = -2.0e-8*ProduceBCjCk
    J[7][7] = -2.0e-8*HelperCCk - 1.0e-5*U19
    J[7][8] = 0
    J[7][9] = 0
    J[7][10] = -1.0e-5*ProduceBCjCk
    J[7][11] = 0
    J[7][12] = 0
    J[7][13] = 1.0e-5*Cj
    J[7][14] = 0
    J[7][15] = 0
    J[7][16] = 0
    J[7][17] = 0
    J[7][18] = 0
    J[7][19] = 0
    J[7][20] = 0
    J[7][21] = 0
    J[7][22] = 0
    J[7][23] = 0
    J[7][24] = 0
    J[7][25] = 0
    J[7][26] = 0
    J[7][27] = 0
    J[8][0] = -8.0e-6*ReactCBCj
    J[8][1] = -8.0e-6*ReactCBCj
    J[8][2] = 0
    J[8][3] = 0
    J[8][4] = 1.0e-5*U12 + 1.0e-5*U8
    J[8][5] = 0
    J[8][6] = 0
    J[8][7] = 0
    J[8][8] = -8.0e-6*Cj - 8.0e-6*Ck
    J[8][9] = 1.0e-5*BackBC
    J[8][10] = 0
    J[8][11] = 0
    J[8][12] = 0
    J[8][13] = 0
    J[8][14] = 0
    J[8][15] = 1.0e-5*BackBC
    J[8][16] = 0
    J[8][17] = 0
    J[8][18] = 0
    J[8][19] = 0
    J[8][20] = 0
    J[8][21] = 0
    J[8][22] = 0
    J[8][23] = 0
    J[8][24] = 0
    J[8][25] = 0
    J[8][26] = 0
    J[8][27] = 0
    J[9][0] = 8.0e-6*ReactCBCj
    J[9][1] = 0
    J[9][2] = 0
    J[9][3] = 0
    J[9][4] = -1.0e-5*U12
    J[9][5] = -1.0e-5*U12
    J[9][6] = 0
    J[9][7] = 0
    J[9][8] = 8.0e-6*Cj
    J[9][9] = -1.0e-5*BackBC - 1.0e-5*HelperB
    J[9][10] = 0
    J[9][11] = 0
    J[9][12] = 0
    J[9][13] = 0
    J[9][14] = 0
    J[9][15] = 0
    J[9][16] = 0
    J[9][17] = 0
    J[9][18] = 0
    J[9][19] = 0
    J[9][20] = 0
    J[9][21] = 0
    J[9][22] = 0
    J[9][23] = 0
    J[9][24] = 0
    J[9][25] = 0
    J[9][26] = 0
    J[9][27] = 0
    J[10][0] = 1.0e-5*U41
    J[10][1] = 0
    J[10][2] = 0
    J[10][3] = 0
    J[10][4] = 0
    J[10][5] = 1.0e-5*U12 + 1.0e-5*U8
    J[10][6] = 0
    J[10][7] = -1.0e-5*U19
    J[10][8] = 0
    J[10][9] = 1.0e-5*HelperB
    J[10][10] = -1.0e-5*ProduceBCjCk
    J[10][11] = 0
    J[10][12] = 0
    J[10][13] = 1.0e-5*Cj
    J[10][14] = 0
    J[10][15] = 1.0e-5*HelperB
    J[10][16] = 0
    J[10][17] = 0
    J[10][18] = 0
    J[10][19] = 0
    J[10][20] = 0
    J[10][21] = 0
    J[10][22] = 0
    J[10][23] = 0
    J[10][24] = 0
    J[10][25] = 0
    J[10][26] = 0
    J[10][27] = 0
    J[11][0] = 0
    J[11][1] = 0
    J[11][2] = 0
    J[11][3] = 0
    J[11][4] = 0
    J[11][5] = 1.0e-5*U12
    J[11][6] = 0
    J[11][7] = 0
    J[11][8] = 0
    J[11][9] = 1.0e-5*HelperB
    J[11][10] = 0
    J[11][11] = 0
    J[11][12] = 0
    J[11][13] = 0
    J[11][14] = 0
    J[11][15] = 0
    J[11][16] = 0
    J[11][17] = 0
    J[11][18] = 0
    J[11][19] = 0
    J[11][20] = 0
    J[11][21] = 0
    J[11][22] = 0
    J[11][23] = 0
    J[11][24] = 0
    J[11][25] = 0
    J[11][26] = 0
    J[11][27] = 0
    J[12][0] = 0
    J[12][1] = 0
    J[12][2] = 0
    J[12][3] = 0
    J[12][4] = 0
    J[12][5] = 1.0e-5*U8
    J[12][6] = 0
    J[12][7] = 0
    J[12][8] = 0
    J[12][9] = 0
    J[12][10] = 0
    J[12][11] = 0
    J[12][12] = 0
    J[12][13] = 0
    J[12][14] = 0
    J[12][15] = 1.0e-5*HelperB
    J[12][16] = 0
    J[12][17] = 0
    J[12][18] = 0
    J[12][19] = 0
    J[12][20] = 0
    J[12][21] = 0
    J[12][22] = 0
    J[12][23] = 0
    J[12][24] = 0
    J[12][25] = 0
    J[12][26] = 0
    J[12][27] = 0
    J[13][0] = -1.0e-5*U41
    J[13][1] = 0
    J[13][2] = 0
    J[13][3] = 0
    J[13][4] = 0
    J[13][5] = 0
    J[13][6] = -1.0e-5*U41
    J[13][7] = 1.0e-5*U19
    J[13][8] = 0
    J[13][9] = 0
    J[13][10] = 1.0e-5*ProduceBCjCk
    J[13][11] = 0
    J[13][12] = 0
    J[13][13] = -1.0e-5*Cj - 1.0e-5*HelperCCk
    J[13][14] = 0
    J[13][15] = 0
    J[13][16] = 0
    J[13][17] = 0
    J[13][18] = 0
    J[13][19] = 0
    J[13][20] = 0
    J[13][21] = 0
    J[13][22] = 0
    J[13][23] = 0
    J[13][24] = 0
    J[13][25] = 0
    J[13][26] = 0
    J[13][27] = 0
    J[14][0] = 0
    J[14][1] = 0
    J[14][2] = 0
    J[14][3] = 0
    J[14][4] = 0
    J[14][5] = 0
    J[14][6] = 1.0e-5*U41
    J[14][7] = 0
    J[14][8] = 0
    J[14][9] = 0
    J[14][10] = 0
    J[14][11] = 0
    J[14][12] = 0
    J[14][13] = 1.0e-5*HelperCCk
    J[14][14] = 0
    J[14][15] = 0
    J[14][16] = 0
    J[14][17] = 0
    J[14][18] = 0
    J[14][19] = 0
    J[14][20] = 0
    J[14][21] = 0
    J[14][22] = 0
    J[14][23] = 0
    J[14][24] = 0
    J[14][25] = 0
    J[14][26] = 0
    J[14][27] = 0
    J[15][0] = 0
    J[15][1] = 8.0e-6*ReactCBCj
    J[15][2] = 0
    J[15][3] = 0
    J[15][4] = -1.0e-5*U8
    J[15][5] = -1.0e-5*U8
    J[15][6] = 0
    J[15][7] = 0
    J[15][8] = 8.0e-6*Ck
    J[15][9] = 0
    J[15][10] = 0
    J[15][11] = 0
    J[15][12] = 0
    J[15][13] = 0
    J[15][14] = 0
    J[15][15] = -1.0e-5*BackBC - 1.0e-5*HelperB
    J[15][16] = 0
    J[15][17] = 0
    J[15][18] = 0
    J[15][19] = 0
    J[15][20] = 0
    J[15][21] = 0
    J[15][22] = 0
    J[15][23] = 0
    J[15][24] = 0
    J[15][25] = 0
    J[15][26] = 0
    J[15][27] = 0
    J[16][0] = 0
    J[16][1] = 0
    J[16][2] = 0
    J[16][3] = 0.0008*shReactCBCj
    J[16][4] = 0
    J[16][5] = 0
    J[16][6] = 0
    J[16][7] = 0
    J[16][8] = 0
    J[16][9] = 0
    J[16][10] = 0
    J[16][11] = 0
    J[16][12] = 0
    J[16][13] = 0
    J[16][14] = 0
    J[16][15] = 0
    J[16][16] = -0.001*shBackBC - 0.001*shHelperB
    J[16][17] = 0
    J[16][18] = 0
    J[16][19] = 0
    J[16][20] = 0
    J[16][21] = 0
    J[16][22] = 0
    J[16][23] = -0.001*US10
    J[16][24] = -0.001*US10
    J[16][25] = 0
    J[16][26] = 0
    J[16][27] = 0.0008*shCk
    J[17][0] = 0
    J[17][1] = 0
    J[17][2] = 0.001*US37
    J[17][3] = 0
    J[17][4] = 0
    J[17][5] = 0
    J[17][6] = 0
    J[17][7] = 0
    J[17][8] = 0
    J[17][9] = 0
    J[17][10] = 0
    J[17][11] = 0
    J[17][12] = 0
    J[17][13] = 0
    J[17][14] = 0
    J[17][15] = 0
    J[17][16] = 0.001*shHelperB
    J[17][17] = -0.001*shProduceBCjCk
    J[17][18] = 0
    J[17][19] = 0
    J[17][20] = 0.001*shCj
    J[17][21] = 0
    J[17][22] = 0.001*shHelperB
    J[17][23] = 0
    J[17][24] = 0.001*US10 + 0.001*US5
    J[17][25] = 0
    J[17][26] = -0.001*US22
    J[17][27] = 0
    J[18][0] = 0
    J[18][1] = 0
    J[18][2] = 0
    J[18][3] = 0
    J[18][4] = 0
    J[18][5] = 0
    J[18][6] = 0
    J[18][7] = 0
    J[18][8] = 0
    J[18][9] = 0
    J[18][10] = 0
    J[18][11] = 0
    J[18][12] = 0
    J[18][13] = 0
    J[18][14] = 0
    J[18][15] = 0
    J[18][16] = 0.001*shHelperB
    J[18][17] = 0
    J[18][18] = 0
    J[18][19] = 0
    J[18][20] = 0
    J[18][21] = 0
    J[18][22] = 0
    J[18][23] = 0
    J[18][24] = 0.001*US10
    J[18][25] = 0
    J[18][26] = 0
    J[18][27] = 0
    J[19][0] = 0
    J[19][1] = 0
    J[19][2] = 0
    J[19][3] = 0
    J[19][4] = 0
    J[19][5] = 0
    J[19][6] = 0
    J[19][7] = 0
    J[19][8] = 0
    J[19][9] = 0
    J[19][10] = 0
    J[19][11] = 0
    J[19][12] = 0
    J[19][13] = 0
    J[19][14] = 0
    J[19][15] = 0
    J[19][16] = 0
    J[19][17] = 0
    J[19][18] = 0
    J[19][19] = 0
    J[19][20] = 0
    J[19][21] = 0
    J[19][22] = 0.001*shHelperB
    J[19][23] = 0
    J[19][24] = 0.001*US5
    J[19][25] = 0
    J[19][26] = 0
    J[19][27] = 0
    J[20][0] = 0
    J[20][1] = 0
    J[20][2] = -0.001*US37
    J[20][3] = 0
    J[20][4] = 0
    J[20][5] = 0
    J[20][6] = 0
    J[20][7] = 0
    J[20][8] = 0
    J[20][9] = 0
    J[20][10] = 0
    J[20][11] = 0
    J[20][12] = 0
    J[20][13] = 0
    J[20][14] = 0
    J[20][15] = 0
    J[20][16] = 0
    J[20][17] = 0.001*shProduceBCjCk
    J[20][18] = 0
    J[20][19] = 0
    J[20][20] = -0.001*shCj - 0.001*shHelperCCk
    J[20][21] = 0
    J[20][22] = 0
    J[20][23] = 0
    J[20][24] = 0
    J[20][25] = -0.001*US37
    J[20][26] = 0.001*US22
    J[20][27] = 0
    J[21][0] = 0
    J[21][1] = 0
    J[21][2] = 0
    J[21][3] = 0
    J[21][4] = 0
    J[21][5] = 0
    J[21][6] = 0
    J[21][7] = 0
    J[21][8] = 0
    J[21][9] = 0
    J[21][10] = 0
    J[21][11] = 0
    J[21][12] = 0
    J[21][13] = 0
    J[21][14] = 0
    J[21][15] = 0
    J[21][16] = 0
    J[21][17] = 0
    J[21][18] = 0
    J[21][19] = 0
    J[21][20] = 0.001*shHelperCCk
    J[21][21] = 0
    J[21][22] = 0
    J[21][23] = 0
    J[21][24] = 0
    J[21][25] = 0.001*US37
    J[21][26] = 0
    J[21][27] = 0
    J[22][0] = 0
    J[22][1] = 0
    J[22][2] = 0.0008*shReactCBCj
    J[22][3] = 0
    J[22][4] = 0
    J[22][5] = 0
    J[22][6] = 0
    J[22][7] = 0
    J[22][8] = 0
    J[22][9] = 0
    J[22][10] = 0
    J[22][11] = 0
    J[22][12] = 0
    J[22][13] = 0
    J[22][14] = 0
    J[22][15] = 0
    J[22][16] = 0
    J[22][17] = 0
    J[22][18] = 0
    J[22][19] = 0
    J[22][20] = 0
    J[22][21] = 0
    J[22][22] = -0.001*shBackBC - 0.001*shHelperB
    J[22][23] = -0.001*US5
    J[22][24] = -0.001*US5
    J[22][25] = 0
    J[22][26] = 0
    J[22][27] = 0.0008*shCj
    J[23][0] = 0
    J[23][1] = 0
    J[23][2] = 0.0008*shReactCBCj
    J[23][3] = 0.0008*shReactCBCj
    J[23][4] = 0
    J[23][5] = 0
    J[23][6] = 0
    J[23][7] = 0
    J[23][8] = 0
    J[23][9] = 0
    J[23][10] = 0
    J[23][11] = 0
    J[23][12] = 0
    J[23][13] = 0
    J[23][14] = 0
    J[23][15] = 0
    J[23][16] = -0.001*shBackBC
    J[23][17] = 0
    J[23][18] = 0
    J[23][19] = 0
    J[23][20] = 0
    J[23][21] = 0
    J[23][22] = -0.001*shBackBC
    J[23][23] = -0.001*US10 - 0.001*US5
    J[23][24] = 0
    J[23][25] = 0
    J[23][26] = 0
    J[23][27] = 0.0008*shCj + 0.0008*shCk
    J[24][0] = 0
    J[24][1] = 0
    J[24][2] = 0
    J[24][3] = 0
    J[24][4] = 0
    J[24][5] = 0
    J[24][6] = 0
    J[24][7] = 0
    J[24][8] = 0
    J[24][9] = 0
    J[24][10] = 0
    J[24][11] = 0
    J[24][12] = 0
    J[24][13] = 0
    J[24][14] = 0
    J[24][15] = 0
    J[24][16] = -0.001*shHelperB
    J[24][17] = 0
    J[24][18] = 0
    J[24][19] = 0
    J[24][20] = 0
    J[24][21] = 0
    J[24][22] = -0.001*shHelperB
    J[24][23] = 0
    J[24][24] = -0.001*US10 - 0.001*US5
    J[24][25] = 0
    J[24][26] = 0
    J[24][27] = 0
    J[25][0] = 0
    J[25][1] = 0
    J[25][2] = 0
    J[25][3] = 0
    J[25][4] = 0
    J[25][5] = 0
    J[25][6] = 0
    J[25][7] = 0
    J[25][8] = 0
    J[25][9] = 0
    J[25][10] = 0
    J[25][11] = 0
    J[25][12] = 0
    J[25][13] = 0
    J[25][14] = 0
    J[25][15] = 0
    J[25][16] = 0
    J[25][17] = 0
    J[25][18] = 0
    J[25][19] = 0
    J[25][20] = -0.001*shHelperCCk
    J[25][21] = 0
    J[25][22] = 0
    J[25][23] = 0
    J[25][24] = 0
    J[25][25] = -0.001*US37 - 2.0e-8*shProduceBCjCk
    J[25][26] = -2.0e-8*shHelperCCk
    J[25][27] = 0
    J[26][0] = 0
    J[26][1] = 0
    J[26][2] = 0.001*US37
    J[26][3] = 0
    J[26][4] = 0
    J[26][5] = 0
    J[26][6] = 0
    J[26][7] = 0
    J[26][8] = 0
    J[26][9] = 0
    J[26][10] = 0
    J[26][11] = 0
    J[26][12] = 0
    J[26][13] = 0
    J[26][14] = 0
    J[26][15] = 0
    J[26][16] = 0
    J[26][17] = -0.001*shProduceBCjCk
    J[26][18] = 0
    J[26][19] = 0
    J[26][20] = 0.001*shCj
    J[26][21] = 0
    J[26][22] = 0
    J[26][23] = 0
    J[26][24] = 0
    J[26][25] = -2.0e-8*shProduceBCjCk
    J[26][26] = -0.001*US22 - 2.0e-8*shHelperCCk
    J[26][27] = 0
    J[27][0] = 0
    J[27][1] = 0
    J[27][2] = -0.0008*shReactCBCj
    J[27][3] = -0.0008*shReactCBCj
    J[27][4] = 0
    J[27][5] = 0
    J[27][6] = 0
    J[27][7] = 0
    J[27][8] = 0
    J[27][9] = 0
    J[27][10] = 0
    J[27][11] = 0
    J[27][12] = 0
    J[27][13] = 0
    J[27][14] = 0
    J[27][15] = 0
    J[27][16] = 0.001*shBackBC
    J[27][17] = 0
    J[27][18] = 0
    J[27][19] = 0
    J[27][20] = 0
    J[27][21] = 0
    J[27][22] = 0.001*shBackBC
    J[27][23] = 0.001*US10 + 0.001*US5
    J[27][24] = 0
    J[27][25] = 0
    J[27][26] = 0
    J[27][27] = -0.0008*shCj - 0.0008*shCk
    return J


def add_integrator_args(parser):
    """ODE integration aruments."""
    solver = parser.add_argument_group('odeint parameters')
    plotter = parser.add_argument_group('plotting parameters')

    # required: simulation time and output settings
    solver.add_argument("--t0", type=float, default=0, metavar='<flt>',
            help="First time point of the time-course.")
    solver.add_argument("--t8", type=float, default=100, metavar='<flt>',
            help="End point of simulation time.")
    plotter.add_argument("--t-lin", type=int, default=500, metavar='<int>',
            help="Returns --t-lin evenly spaced numbers on a linear scale from --t0 to --t8.")
    plotter.add_argument("--t-log", type=int, default=None, metavar='<int>',
            help="Returns --t-log evenly spaced numbers on a logarithmic scale from --t0 to --t8.")

    # required: initial concentration vector
    solver.add_argument("--p0", nargs='+', metavar='<int/str>=<flt>',
            help="""Vector of initial species concentrations. 
            E.g. \"--p0 1=0.5 3=0.7\" stands for 1st species at a concentration of 0.5 
            and 3rd species at a concentration of 0.7. You may chose to address species
            directly by name, e.g.: --p0 C=0.5.""")
    # advanced: scipy.integrate.odeint parameters
    solver.add_argument("-a", "--atol", type=float, default=None, metavar='<flt>',
            help="Specify absolute tolerance for the solver.")
    solver.add_argument("-r", "--rtol", type=float, default=None, metavar='<flt>',
            help="Specify relative tolerance for the solver.")
    solver.add_argument("--mxstep", type=int, default=0, metavar='<int>',
            help="Maximum number of steps allowed for each integration point in t.")

    # optional: choose output formats
    plotter.add_argument("--list-labels", action='store_true',
            help="Print all species and exit.")
    plotter.add_argument("--labels", nargs='+', default=[], metavar='<str>+',
            help="""Specify the (order of) species which should appear in the pyplot legend, 
            as well as the order of species for nxy output format.""")
    plotter.add_argument("--labels-strict", action='store_true',
            help="""When using pyplot, only plot tracjectories corresponding to labels,
            when using nxy, only print the trajectories corresponding to labels.""")
 
    plotter.add_argument("--nxy", action='store_true',
            help="Print time course to STDOUT in nxy format.")
    plotter.add_argument("--header", action='store_true',
            help="Print header for trajectories.")

    plotter.add_argument("--pyplot", default='', metavar='<str>',
            help="Specify a filename to plot the ODE simulation.")
    plotter.add_argument("--pyplot-xlim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the x-axis.")
    plotter.add_argument("--pyplot-ylim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the y-axis.")
    plotter.add_argument("--pyplot-labels", nargs='+', default=[], metavar='<str>+',
            help=argparse.SUPPRESS)
    return

def flint(inp):
    return int(float(inp)) if float(inp) == int(float(inp)) else float(inp)

def set_logger(verbose, logfile):
    # ~~~~~~~~~~~~~
    # Logging Setup 
    # ~~~~~~~~~~~~~
    logger.setLevel(logging.DEBUG)
    handler = logging.FileHandler(logfile) if logfile else logging.StreamHandler()
    if verbose == 0:
        handler.setLevel(logging.WARNING)
    elif verbose == 1:
        handler.setLevel(logging.INFO)
    elif verbose == 2:
        handler.setLevel(logging.DEBUG)
    elif verbose >= 3:
        handler.setLevel(logging.NOTSET)
    formatter = logging.Formatter('%(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)


def integrate(args, setlogger = False):
    """Main interface to solve the ODE-system.

    Args:
      args (:obj:`argparse.ArgumentParser()`): An argparse object containing all of
        the arguments of :obj:`crnsimulator.add_integrator_args()`.

    Prints:
      - plot files
      - time-course

    Returns:
      Nothing
    """
    if setlogger:
        set_logger(args.verbose, args.logfile)

    if args.pyplot_labels:
        logger.warning('Deprecated argument: --pyplot_labels.')

    svars = ["Cj", "Ck", "shCj", "shCk", "BackBC", "HelperB", "HelperCCk", "ProduceBCjCk", "ReactCBCj", "U12", "U19", "U20", "U30", "U41", "U52", "U8", "US10", "US22", "US23", "US25", "US37", "US45", "US5", "shBackBC", "shHelperB", "shHelperCCk", "shProduceBCjCk", "shReactCBCj"]

    p0 = [0] * len(svars)
    p0[0] = 1.0
    p0[4] = 200.0
    p0[5] = 150.0
    p0[6] = 150.0
    p0[7] = 200.0
    p0[8] = 200.0
    p0[23] = 200.0
    p0[24] = 150.0
    p0[25] = 150.0
    p0[26] = 200.0
    p0[27] = 200.0
    
    const = None
    #<&>CONSTANT_SPECIES_INFO<&>#
    if args.p0:
        for term in args.p0:
            p, o = term.split('=')
            try:
                pi = svars.index(p)
            except ValueError as e:
                pi = int(p) - 1
            finally:
                p0[pi] = flint(o)
    else:
        msg = 'Specify a vector of initial concentrations: ' + \
                'e.g. --p0 1=0.1 2=0.005 3=1e-6 (see --help)'
        if sum(p0) == 0:
            logger.warning(msg)
            args.list_labels = True
        else:
            logger.info(msg)

    if args.list_labels:
        print('List of variables and initial concentrations:')
        for e, v in enumerate(svars, 1):
            if args.labels_strict and e > len(args.labels):
                break
            print(f'{e} {v} {p0[e-1]} {"constant" if const and const[e-1] else ""}')
        raise SystemExit('Initial concentrations can be overwritten by --p0 argument')

    if not args.nxy and not args.pyplot:
        logger.warning('Use --pyplot and/or --nxy to plot your results.')

    if not args.t8:
        raise ODETemplateError('Specify a valid end-time for the simulation: --t8 <flt>')

    if args.t_log:
        if args.t0 == 0:
            raise ODETemplateError('--t0 cannot be 0 when using log-scale!')
        time = np.logspace(np.log10(args.t0), np.log10(args.t8), num=args.t_log)
    elif args.t_lin:
        time = np.linspace(args.t0, args.t8, num=args.t_lin)
    else:
        raise ODETemplateError('Please specify either --t-lin or --t-log. (see --help)')

    # It would be nice if it is possible to read alternative rates from a file instead.
    # None triggers the default-rates that are hard-coded in the (this) library file.
    rates = None

    logger.info(f'Initial concentrations: {list(zip(svars, p0))}')
    # TODO: logging should report more info on parameters.

    ny = odeint(odesystem,
        np.array(p0), time, (rates, ), Dfun = jacobian,
        atol=args.atol, rtol=args.rtol, mxstep=args.mxstep).T

    # Output
    if args.nxy and args.labels_strict:
        end = len(args.labels)
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars[:end]]))
        for i in zip(time, *ny[:end]):
            print(' '.join(map("{:.9e}".format, i)))
    elif args.nxy:
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars]))
        for i in zip(time, *ny):
            print(' '.join(map("{:.9e}".format, i)))

    if args.pyplot:
        from crnsimulator.plotting import ode_plotter
        plotfile = ode_plotter(args.pyplot, time, ny, svars,
                               log=True if args.t_log else False,
                               labels=set(args.labels),
                               xlim = args.pyplot_xlim,
                               ylim = args.pyplot_ylim,
                               labels_strict = args.labels_strict)
        logger.info(f"Plotting successfull. Wrote plot to file: {plotfile}")

    return zip(time, *ny)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v", "--verbose", action='count', default = 0,
        help = "Print logging output. (-vv increases verbosity.)")
    parser.add_argument('--logfile', default = '', action = 'store', metavar = '<str>',
        help = """Redirect logging information to a file.""")
    add_integrator_args(parser)
    args = parser.parse_args()
    integrate(args, setlogger = True)

